In [13]:
from google.colab import files
upload = files.upload()

Saving chrun_modeling.csv to chrun_modeling (1).csv


In [14]:
!ls


'chrun_modeling (1).csv'   chrun_modeling.csv   sample_data


In [15]:
!pwd


/content


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [17]:
data = pd.read_csv('chrun_modeling.csv')
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [18]:
print("Total shape   : ", data.shape)
print("*"*50)
print("Total Columns : ", data.columns )
print("*"*50)
print(data.info)

Total shape   :  (10000, 14)
**************************************************
Total Columns :  Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')
**************************************************
<bound method DataFrame.info of       RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       999

In [37]:
X = data.iloc[:,3:13].values
y = data.iloc[:,13].values
len(X[:10][0])

10

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer


In [0]:
label_encoder_x_1 = LabelEncoder()
X[:,1] = label_encoder_x_1.fit_transform(X[:,1])

label_encoder_x_2 = LabelEncoder()
X[:,2] = label_encoder_x_2.fit_transform(X[:,2])

tranformer = ColumnTransformer(transformers=[("Geography", OneHotEncoder(), [1])], remainder='passthrough')
X = tranformer.fit_transform(X.tolist())
X = X.astype('float64') 

In [39]:
X[:5][0]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [0]:
from sklearn.model_selection import train_test_split


In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
sc = StandardScaler()
x_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Model Building using Keras

In [31]:
import keras

Using TensorFlow backend.


In [0]:
from keras.models import  Sequential
from keras.layers import Dense

In [43]:
cls= Sequential()

#Input layers
cls.add(Dense(output_dim=6, init = 'uniform', activation='relu', input_dim = 12))

#Middle or Hidden Layers
cls.add(Dense(output_dim = 6, init= 'uniform', activation= 'relu'))

# Output Layers
cls.add(Dense(output_dim = 1, init='uniform', activation= 'sigmoid'))

#Compile model
cls.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.


In [44]:
## Traning the model now
cls.fit(X_train, y_train, batch_size=20, epochs=100)





Epoch 1/100





8000/8000 [==============================] - 10s 1ms/step - loss: 0.5632 - acc: 0.7876
Epoch 2/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.5219 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.5176 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 224us/step - loss: 0.5139 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.5090 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.5066 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 2s 248us/step - loss: 0.5064 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 2s 239us/step - loss: 0.5061 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 2s 238us/step - loss: 0.5047 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 2s 235us/step - loss: 0.5067 - acc:

In [46]:
y_pred = cls.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [47]:
len(y_pred)

2000

In [0]:
from sklearn.metrics import confusion_matrix

In [49]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[1595,    0],
       [ 405,    0]])

In [0]:
from sklearn.metrics import accuracy_score

In [53]:
ac = accuracy_score(y_test, y_pred)
ac*100

79.75